//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///    Clase de recurso fuertemente tipado para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strText() {
        }
        
        /// <summary>
        ///    Devuelve la instancia ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.strText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///    búsquedas de recursos usando esta clase de recursos fuertemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a No existe el registro.
        /// </summary>
        internal static string msgNoRecordsFound {
            get {
                return ResourceManager.GetString("msgNoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Campo Obligatorio.
        /// </summary>
        internal static string msgRequiredField {
            get {
                return ResourceManager.GetString("msgRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string strAcept {
            get {
                return ResourceManager.GetString("strAcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string strClose {
            get {
                return ResourceManager.GetString("strClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Placas.
        /// </summary>
        internal static string strLicenseNumberPlate {
            get {
                return ResourceManager.GetString("strLicenseNumberPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Ubicacion.
        /// </summary>
        internal static string strLocation {
            get {
                return ResourceManager.GetString("strLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Modelo.
        /// </summary>
        internal static string strModel {
            get {
                return ResourceManager.GetString("strModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Numero de Tienda.
        /// </summary>
        internal static string strNumberStore {
            get {
                return ResourceManager.GetString("strNumberStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Num. Eco..
        /// </summary>
        internal static string strNumEco {
            get {
                return ResourceManager.GetString("strNumEco", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Serial.
        /// </summary>
        internal static string strSerial {
            get {
                return ResourceManager.GetString("strSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Estatus.
        /// </summary>
        internal static string strStatus {
            get {
                return ResourceManager.GetString("strStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Tienda.
        /// </summary>
        internal static string strStore {
            get {
                return ResourceManager.GetString("strStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena traducida similar a Año.
        /// </summary>
        internal static string strYear {
            get {
                return ResourceManager.GetString("strYear", resourceCulture);
            }
        }
    }
}
